// 200 вопросов по Web / Frontend
// Темы: HTML, CSS, JavaScript, TypeScript, React, Vue, браузер, HTTP, безопасность, производительность

const webQuestions = [

  // ── HTML ──────────────────────────────────────────────────────────────────
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что означает аббревиатура HTML?",
    options: ["HyperText Markup Language", "High Text Machine Language", "Hyper Transfer Markup Logic", "HyperText Modern Language"],
    answer: 0,
    explanation: "HTML — HyperText Markup Language, язык разметки гипертекста, основа любой веб-страницы.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Какой тег используется для создания гиперссылки?",
    options: ["<link>", "<href>", "<a>", "<url>"],
    answer: 2,
    explanation: "<a href='...'>текст</a> — тег anchor создаёт кликабельную ссылку.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое семантический HTML?",
    options: ["HTML с инлайн-стилями", "Использование тегов по их смысловому значению (<article>, <nav>, <header>)", "Минифицированный HTML", "HTML без комментариев"],
    answer: 1,
    explanation: "Семантические теги описывают смысл контента, улучшают SEO и доступность.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Какой атрибут делает поле формы обязательным?",
    options: ["mandatory", "required", "validate", "must"],
    answer: 1,
    explanation: "Атрибут required запрещает отправку формы, если поле не заполнено.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что делает тег <meta charset='UTF-8'>?",
    options: ["Задаёт цвет фона", "Указывает кодировку документа", "Подключает шрифт", "Задаёт язык страницы"],
    answer: 1,
    explanation: "UTF-8 — универсальная кодировка, поддерживающая все символы мира. Без неё кириллица и другие символы отображаются некорректно.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Какой тег используется для встраивания видео на страницу?",
    options: ["<media>", "<film>", "<video>", "<embed-video>"],
    answer: 2,
    explanation: "Тег <video> с атрибутом src или вложенными <source> позволяет встроить видео прямо в HTML5.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Чем отличается <div> от <span>?",
    options: ["Нет разницы", "<div> — блочный элемент, <span> — строчный", "<span> больше по размеру", "<div> только для текста"],
    answer: 1,
    explanation: "<div> занимает всю ширину строки (block), <span> — только ширину содержимого (inline).",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое data-атрибуты в HTML?",
    options: ["Атрибуты только для форм", "Пользовательские атрибуты для хранения данных прямо в HTML-элементах", "Атрибуты для SEO", "Атрибуты для стилизации"],
    answer: 1,
    explanation: "data-* атрибуты позволяют хранить произвольные данные в элементах: <div data-user-id='42'>. Доступны через dataset в JS.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Какой тег задаёт заголовок вкладки браузера?",
    options: ["<header>", "<h1>", "<title>", "<head>"],
    answer: 2,
    explanation: "<title> внутри <head> задаёт текст вкладки браузера и используется поисковиками.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое DOCTYPE в HTML?",
    options: ["Тип CSS-документа", "Объявление, сообщающее браузеру версию HTML", "Комментарий в коде", "Метатег для SEO"],
    answer: 1,
    explanation: "<!DOCTYPE html> сообщает браузеру, что документ написан на HTML5 и включает стандартный режим рендеринга.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Какой атрибут тега <img> важен для доступности?",
    options: ["title", "src", "alt", "width"],
    answer: 2,
    explanation: "alt описывает изображение для скринридеров и отображается, если картинка не загрузилась.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Тег <input type='email'> — что он делает?",
    options: ["Отправляет письмо", "Создаёт поле с валидацией формата email", "Показывает список email", "Подключает почтовый клиент"],
    answer: 1,
    explanation: "type='email' добавляет браузерную валидацию формата email и открывает подходящую клавиатуру на мобильных.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое Shadow DOM?",
    options: ["Скрытый DOM для администраторов", "Инкапсулированное DOM-дерево внутри веб-компонента", "Серверная копия DOM", "Виртуальный DOM React"],
    answer: 1,
    explanation: "Shadow DOM позволяет инкапсулировать разметку и стили внутри веб-компонента, изолируя их от основного документа.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что делает атрибут defer у тега <script>?",
    options: ["Запрещает выполнение скрипта", "Откладывает выполнение скрипта до полного парсинга HTML", "Загружает скрипт асинхронно без гарантии порядка", "Делает скрипт модульным"],
    answer: 1,
    explanation: "defer загружает скрипт параллельно с парсингом HTML, но выполняет его только после полного парсинга, в порядке подключения.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Чем async отличается от defer для тегов <script>?",
    options: ["Нет разницы", "async выполняет скрипт сразу после загрузки, нарушая порядок; defer ждёт конца парсинга", "defer быстрее async", "async только для ES-модулей"],
    answer: 1,
    explanation: "async выполняется как только загрузился (порядок не гарантирован). defer — после парсинга HTML, в порядке подключения.",
  },

  // ── CSS ───────────────────────────────────────────────────────────────────
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое CSS-специфичность (specificity)?",
    options: ["Скорость применения стилей", "Система приоритетов, определяющая какое правило применяется при конфликте", "Порядок подключения CSS-файлов", "Размер CSS-файла"],
    answer: 1,
    explanation: "Специфичность считается по формуле: инлайн > ID > класс/атрибут > тег. При равной специфичности побеждает последнее правило.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что делает display: flex?",
    options: ["Скрывает элемент", "Включает флексбокс-контейнер для гибкого выравнивания дочерних элементов", "Делает элемент фиксированным", "Добавляет анимацию"],
    answer: 1,
    explanation: "Flexbox — одномерная система раскладки. Позволяет легко выравнивать элементы по горизонтали и вертикали.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое CSS Grid?",
    options: ["Сетка для выравнивания текста", "Двумерная система раскладки для строк и столбцов", "Фреймворк Bootstrap", "Тип CSS-анимации"],
    answer: 1,
    explanation: "CSS Grid — двумерная система: управляет одновременно строками и столбцами. Идеален для общего layout страницы.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что означает position: absolute?",
    options: ["Элемент фиксирован относительно окна браузера", "Элемент позиционируется относительно ближайшего предка с position != static", "Элемент вырван из потока и прикреплён к низу страницы", "Элемент занимает всю страницу"],
    answer: 1,
    explanation: "absolute вырывает элемент из потока и позиционирует его относительно ближайшего предка с position: relative/absolute/fixed.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое псевдоэлементы в CSS?",
    options: ["Несуществующие элементы", "::before и ::after — виртуальные элементы, создаваемые через CSS без HTML", "Элементы с классом pseudo", "Теги из HTML5"],
    answer: 1,
    explanation: "::before и ::after добавляют контент до/после элемента только через CSS. Используются для декоративных эффектов.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое CSS-переменные (custom properties)?",
    options: ["Переменные только в SASS", "--name: value — значения, объявляемые в CSS и переиспользуемые через var(--name)", "Переменные в JavaScript", "Атрибуты для анимации"],
    answer: 1,
    explanation: "CSS-переменные объявляются через --name и используются через var(--name). Поддерживают каскад и наследование.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что делает z-index?",
    options: ["Задаёт горизонтальное смещение", "Управляет порядком наложения позиционированных элементов по оси Z", "Задаёт прозрачность", "Управляет z-координатой в 3D"],
    answer: 1,
    explanation: "z-index работает только для позиционированных элементов (не static). Больше значение — элемент ближе к зрителю.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое медиазапросы (media queries)?",
    options: ["Запросы к базе данных", "CSS-правила, применяемые в зависимости от характеристик устройства (ширина, ориентация)", "Запросы к API", "Атрибуты тега <link>"],
    answer: 1,
    explanation: "@media (max-width: 768px) { ... } — основа адаптивной вёрстки. Позволяет применять разные стили для разных экранов.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое CSS-каскад?",
    options: ["Анимация падающих элементов", "Алгоритм определения итогового стиля элемента при конфликте правил", "Порядок подключения файлов", "Наследование от родителя"],
    answer: 1,
    explanation: "Каскад определяет победителя при конфликте по: важности (!important), происхождению, специфичности и порядку.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что делает свойство overflow: hidden?",
    options: ["Скрывает элемент", "Обрезает контент, выходящий за границы элемента", "Добавляет скроллбар", "Делает элемент прозрачным"],
    answer: 1,
    explanation: "overflow: hidden скрывает всё, что выходит за границы блока. Также создаёт BFC (Block Formatting Context).",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Чем rem отличается от em в CSS?",
    options: ["Нет разницы", "rem — относительно корневого элемента <html>, em — относительно текущего элемента", "em больше rem", "rem только для мобильных"],
    answer: 1,
    explanation: "em множится при вложенности (1.2em внутри 1.2em = 1.44em), rem всегда от <html> — предсказуемее.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое BFC (Block Formatting Context)?",
    options: ["Bootstrap Framework Component", "Изолированная область, в которой элементы взаимодействуют только друг с другом", "Тип позиционирования", "CSS-функция"],
    answer: 1,
    explanation: "BFC создаётся через overflow:hidden, float, display:flex и др. Внутри BFC floats не вытекают, margin collapsing не происходит.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что делает свойство will-change в CSS?",
    options: ["Запускает анимацию", "Подсказывает браузеру какие свойства будут меняться, для оптимизации рендеринга", "Отменяет переход", "Блокирует изменения"],
    answer: 1,
    explanation: "will-change: transform позволяет браузеру заранее перевести элемент на GPU. Не злоупотребляй — лишний GPU-слой потребляет память.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое CSS-препроцессор?",
    options: ["Инструмент минификации CSS", "Инструмент с переменными, миксинами и вложенностью, компилирующийся в обычный CSS", "Браузерный плагин", "Линтер для CSS"],
    answer: 1,
    explanation: "SASS, LESS, Stylus — популярные препроцессоры. Добавляют переменные, миксины, вложенность, функции и компилируются в чистый CSS.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое CSS-модули (CSS Modules)?",
    options: ["SASS-модули", "Система локального скопирования CSS-классов, предотвращающая конфликты имён", "Встроенные CSS-функции", "npm-пакеты для стилей"],
    answer: 1,
    explanation: "CSS Modules автоматически генерируют уникальные имена классов (Button_button__xK3gD), устраняя глобальные конфликты.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что делает transform: translate(50%, 50%)?",
    options: ["Масштабирует элемент в 2 раза", "Смещает элемент на 50% его собственной ширины и высоты", "Поворачивает элемент", "Скрывает элемент"],
    answer: 1,
    explanation: "translate(50%, 50%) смещает элемент на 50% его ширины и высоты. Классический трюк для центрирования: top:50%, left:50%, translate(-50%,-50%).",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое stacking context в CSS?",
    options: ["Стопка CSS-файлов", "Трёхмерное пространство, в котором элементы упорядочиваются по z-index", "История изменений стилей", "Контекст анимации"],
    answer: 1,
    explanation: "Stacking context создаётся при z-index + position, opacity<1, transform и т.д. z-index работает только внутри своего контекста.",
  },

  // ── JavaScript (основы) ───────────────────────────────────────────────────
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое замыкание (closure) в JavaScript?",
    options: ["Метод закрытия модального окна", "Функция, сохраняющая доступ к переменным из внешней области видимости после её выполнения", "Тип цикла", "Способ импорта модулей"],
    answer: 1,
    explanation: "Замыкание — функция + её лексическое окружение. Внутренняя функция помнит переменные внешней даже после возврата внешней.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что выведет: console.log(typeof null)?",
    options: ["'null'", "'undefined'", "'object'", "'boolean'"],
    answer: 2,
    explanation: "typeof null === 'object' — историческая ошибка JS, существующая с 1995 года. null не является объектом, но typeof возвращает 'object'.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Чем let отличается от var?",
    options: ["Нет разницы", "let имеет блочную область видимости и не поднимается (hoisting) как var", "var быстрее let", "let только для чисел"],
    answer: 1,
    explanation: "var: функциональная область, hoisting, можно переобъявить. let: блочная область, временная мёртвая зона, нельзя переобъявить.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое hoisting в JavaScript?",
    options: ["Загрузка скриптов", "Поднятие объявлений переменных и функций в начало области видимости", "Горячая перезагрузка", "Оптимизация кода"],
    answer: 1,
    explanation: "Объявления var и function поднимаются. var инициализируется как undefined, функции целиком. let/const не инициализируются (TDZ).",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое промис (Promise)?",
    options: ["Функция обратного вызова", "Объект, представляющий результат асинхронной операции (pending/fulfilled/rejected)", "Синхронная функция", "Тип цикла"],
    answer: 1,
    explanation: "Promise — обёртка над асинхронным кодом с тремя состояниями. .then() для успеха, .catch() для ошибки, .finally() для завершения.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что делает Array.prototype.map()?",
    options: ["Фильтрует массив", "Создаёт новый массив, применяя функцию к каждому элементу", "Сортирует массив", "Объединяет массивы"],
    answer: 1,
    explanation: "map() не изменяет исходный массив, возвращает новый той же длины. [1,2,3].map(x => x*2) → [2,4,6].",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Чем null отличается от undefined?",
    options: ["Нет разницы", "undefined — переменная объявлена, но не инициализирована; null — намеренное отсутствие значения", "null больше undefined", "undefined только для объектов"],
    answer: 1,
    explanation: "undefined — значение по умолчанию для необъявленных переменных. null — явное 'пусто', которое разработчик назначает намеренно.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое this в JavaScript?",
    options: ["Ссылка на текущий файл", "Контекст выполнения функции, зависящий от способа её вызова", "Ключевое слово для классов", "Тип переменной"],
    answer: 1,
    explanation: "this в обычной функции — зависит от вызова. В стрелочной — берётся из лексического окружения. В классе — экземпляр класса.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что делает оператор spread (...)?",
    options: ["Создаёт бесконечный цикл", "Разворачивает итерируемый объект в отдельные элементы", "Объявляет функцию", "Комментирует код"],
    answer: 1,
    explanation: "[...arr1, ...arr2] — объединение массивов. {...obj1, ...obj2} — слияние объектов. func(...args) — передача массива как аргументов.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое деструктуризация в JavaScript?",
    options: ["Удаление объекта", "Синтаксис для извлечения значений из массивов и объектов в переменные", "Декомпиляция кода", "Тип цикла"],
    answer: 1,
    explanation: "const {a, b} = obj или const [x, y] = arr — удобный способ 'распаковать' данные без обращения к свойствам вручную.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое Event Loop в JavaScript?",
    options: ["Цикл событий мыши", "Механизм, позволяющий JS выполнять асинхронный код в однопоточной среде", "Тип цикла for", "Обработчик ошибок"],
    answer: 1,
    explanation: "Event Loop проверяет Call Stack — если пуст, берёт задачи из Microtask Queue (промисы) затем Macrotask Queue (setTimeout).",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое prototype в JavaScript?",
    options: ["Первая версия кода", "Объект, от которого другие объекты наследуют свойства и методы", "Тип переменной", "Прототип интерфейса"],
    answer: 1,
    explanation: "Каждый объект имеет [[Prototype]]. Цепочка прототипов (prototype chain) используется для поиска свойств — от объекта к Object.prototype.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что делает метод Array.prototype.reduce()?",
    options: ["Уменьшает массив вдвое", "Сворачивает массив в одно значение, применяя функцию-аккумулятор", "Удаляет дубликаты", "Сортирует по убыванию"],
    answer: 1,
    explanation: "[1,2,3].reduce((acc, x) => acc + x, 0) === 6. reduce — универсальный инструмент: им можно реализовать map, filter и многое другое.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что выведет: console.log(0.1 + 0.2 === 0.3)?",
    options: ["true", "false", "undefined", "NaN"],
    answer: 1,
    explanation: "false! 0.1 + 0.2 = 0.30000000000000004 из-за ошибок представления чисел с плавающей точкой (IEEE 754).",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое WeakMap в JavaScript?",
    options: ["Маленький Map", "Map, где ключи — слабые ссылки на объекты, и они могут быть собраны GC", "Map без методов", "Устаревший тип Map"],
    answer: 1,
    explanation: "WeakMap держит слабые ссылки на ключи-объекты. Когда объект-ключ уничтожается, запись автоматически удаляется. Не итерируемый.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое генераторы (generators) в JavaScript?",
    options: ["Функции для генерации случайных чисел", "Функции с function*, способные приостанавливать выполнение через yield", "Классы-фабрики", "Асинхронные функции"],
    answer: 1,
    explanation: "Генераторы возвращают итератор. Каждый вызов .next() выполняет код до следующего yield, возвращая {value, done}.",
  },

  // ── JavaScript (продвинутый) ───────────────────────────────────────────────
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое debounce?",
    options: ["Отмена запроса", "Откладывание выполнения функции до истечения паузы после последнего вызова", "Тип анимации", "Метод массива"],
    answer: 1,
    explanation: "Debounce: если функцию вызывают часто, она выполняется лишь после паузы. Классика — поиск по вводу: запрос отправляется через 300мс после последнего символа.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Чем debounce отличается от throttle?",
    options: ["Нет разницы", "Throttle ограничивает частоту вызовов (раз в N мс), debounce ждёт паузы", "Throttle только для анимации", "Debounce быстрее"],
    answer: 1,
    explanation: "Throttle: функция выполняется не чаще раза в N мс (scroll, resize). Debounce: выполняется через N мс после последнего вызова (search input).",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое Proxy в JavaScript?",
    options: ["Сетевой прокси-сервер", "Объект-обёртка, перехватывающий операции над другим объектом (get, set, has и др.)", "Тип промиса", "Паттерн проектирования"],
    answer: 1,
    explanation: "Proxy позволяет перехватить любое обращение к объекту. Используется в реактивных системах (Vue 3), валидации, логировании.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое Symbol в JavaScript?",
    options: ["Тип для иконок", "Уникальный и неизменяемый примитивный тип, используемый как ключ объекта", "Строковой тип", "Числовой тип"],
    answer: 1,
    explanation: "Symbol() всегда уникален: Symbol('a') !== Symbol('a'). Используется для скрытых свойств объектов и протоколов итерации (Symbol.iterator).",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что делает Object.freeze()?",
    options: ["Сохраняет объект в localStorage", "Делает объект неизменяемым (нельзя добавить, удалить или изменить свойства)", "Клонирует объект", "Замораживает анимацию"],
    answer: 1,
    explanation: "Object.freeze() создаёт поверхностную заморозку. Вложенные объекты не замораживаются — для глубокой заморозки нужна рекурсия.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое curry (каррирование) в функциональном программировании?",
    options: ["Метод массива", "Преобразование функции с N аргументами в цепочку функций с одним аргументом", "Тип рекурсии", "Паттерн для классов"],
    answer: 1,
    explanation: "curry(add)(1)(2) === add(1, 2). Позволяет создавать частично применённые функции: const add5 = curry(add)(5).",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое memoization (мемоизация) в JavaScript?",
    options: ["Сохранение данных в памяти браузера", "Кэширование результата функции для одинаковых аргументов", "Тип замыкания", "Метод оптимизации DOM"],
    answer: 1,
    explanation: "Мемоизированная функция при повторном вызове с теми же аргументами возвращает кэш вместо вычисления. React.memo и useMemo работают по этому принципу.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое optional chaining (?.) в JavaScript?",
    options: ["Необязательный параметр функции", "Безопасное обращение к свойствам: возвращает undefined вместо ошибки, если объект null/undefined", "Тернарный оператор", "Тип деструктуризации"],
    answer: 1,
    explanation: "user?.address?.city вернёт undefined если user или address равны null/undefined, вместо TypeError.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое nullish coalescing (??) в JavaScript?",
    options: ["Проверка на null", "Возвращает правый операнд если левый null или undefined (в отличие от || который реагирует на любой falsy)", "Тип сравнения", "Логическое И"],
    answer: 1,
    explanation: "0 ?? 'default' === 0 (т.к. 0 не null/undefined). Но 0 || 'default' === 'default' (т.к. 0 falsy). ?? точнее для числовых значений.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое Reflect в JavaScript?",
    options: ["CSS-отражение", "Встроенный объект с методами для перехватываемых операций JS (аналог Proxy handlers)", "Тип рефлексии классов", "Метод для копирования объектов"],
    answer: 1,
    explanation: "Reflect.get(obj, 'key') — то же что obj.key, но как функция. Используется совместно с Proxy для корректной передачи операций.",
  },

  // ── TypeScript ────────────────────────────────────────────────────────────
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое TypeScript?",
    options: ["Новый язык программирования", "Надмножество JavaScript с статической типизацией, компилирующееся в JS", "Фреймворк для тестирования", "Альтернатива Node.js"],
    answer: 1,
    explanation: "TypeScript добавляет к JS статические типы, интерфейсы, дженерики. Компилируется в чистый JS — браузеры TypeScript не понимают.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое interface в TypeScript?",
    options: ["UI-компонент", "Описание формы объекта или контракт для классов", "Тип функции", "Аналог enum"],
    answer: 1,
    explanation: "interface описывает структуру объекта. В отличие от type, интерфейсы можно расширять (extends) и слоянием объявлений (declaration merging).",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Чем type отличается от interface в TypeScript?",
    options: ["Нет разницы", "type может описывать примитивы, union, intersection; interface — только формы объектов и поддерживает merging", "interface быстрее", "type только для функций"],
    answer: 1,
    explanation: "type шире: type ID = string | number. interface лучше для объектов и классов. Оба расширяемы, но по-разному.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое generics (дженерики) в TypeScript?",
    options: ["Общие настройки компилятора", "Параметрические типы для написания переиспользуемого типобезопасного кода", "Тип для любых значений", "Встроенные типы"],
    answer: 1,
    explanation: "function identity<T>(arg: T): T {} — T заменяется реальным типом при вызове. Как шаблоны в C++, без потери типобезопасности.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое union type в TypeScript?",
    options: ["Объединение объектов", "Тип, который может быть одним из нескольких типов: string | number", "Пересечение типов", "Тип для массивов"],
    answer: 1,
    explanation: "string | number означает 'строка или число'. При работе с union нужно сужение типа (narrowing): typeof, instanceof, discriminated union.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что делает оператор as в TypeScript?",
    options: ["Переименовывает переменную", "Явно приводит тип (type assertion), говоря компилятору 'доверяй мне'", "Создаёт псевдоним", "Импортирует тип"],
    answer: 1,
    explanation: "const el = document.getElementById('id') as HTMLInputElement. Снимает ответственность с компилятора — если ошибётся разработчик, получит runtime-ошибку.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое readonly в TypeScript?",
    options: ["Только для чтения файл", "Модификатор, запрещающий изменение свойства после инициализации", "Тип для констант", "Метод объекта"],
    answer: 1,
    explanation: "interface User { readonly id: number } — id нельзя изменить после создания объекта. Компилятор покажет ошибку при попытке.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое Partial<T> в TypeScript?",
    options: ["Частичная компиляция", "Utility-тип, делающий все свойства типа T необязательными", "Тип для неполных объектов", "Аналог any"],
    answer: 1,
    explanation: "Partial<User> = { id?: number; name?: string }. Удобен для функций обновления, где передаётся только часть полей.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое Pick<T, K> в TypeScript?",
    options: ["Выбор случайного элемента", "Utility-тип, создающий новый тип из подмножества свойств T", "Метод массива", "Оператор деструктуризации"],
    answer: 1,
    explanation: "Pick<User, 'id' | 'name'> создаёт тип только с полями id и name. Полезен для DTO и API-контрактов.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое enum в TypeScript?",
    options: ["Тип для чисел", "Именованный набор констант", "Тип для строк", "Аналог interface"],
    answer: 1,
    explanation: "enum Direction { Up, Down, Left, Right }. По умолчанию числовой (0, 1, 2...). Можно использовать строковые: enum Dir { Up = 'UP' }.",
  },

  // ── React ─────────────────────────────────────────────────────────────────
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое JSX?",
    options: ["Новый язык программирования", "Синтаксическое расширение JS, позволяющее писать HTML-подобный код в JavaScript", "JSON с расширением", "Фреймворк"],
    answer: 1,
    explanation: "JSX компилируется в React.createElement(). <div className='x'> → React.createElement('div', {className: 'x'}).",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое хуки (hooks) в React?",
    options: ["Плагины для React", "Функции (useState, useEffect и др.), позволяющие использовать state и lifecycle в функциональных компонентах", "Методы классовых компонентов", "Тип пропсов"],
    answer: 1,
    explanation: "Хуки появились в React 16.8. Правила: вызывать только на верхнем уровне компонента, только внутри функциональных компонентов.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что делает useState?",
    options: ["Хранит состояние в localStorage", "Возвращает пару [значение, сеттер], при изменении которой компонент перерендеривается", "Подписывается на глобальный state", "Управляет пропсами"],
    answer: 1,
    explanation: "const [count, setCount] = useState(0). Вызов сеттера вызывает ре-рендер компонента с новым значением.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Когда используется useEffect?",
    options: ["Для оптимизации рендера", "Для выполнения побочных эффектов: запросы к API, подписки, таймеры, работа с DOM", "Для хранения состояния", "Для передачи данных"],
    answer: 1,
    explanation: "useEffect(() => {}, [deps]). Зависимости контролируют когда запускается. Возвращаемая функция — cleanup (отписка, очистка).",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое useCallback?",
    options: ["Хук для запросов", "Мемоизирует функцию, чтобы она не пересоздавалась при каждом рендере", "Аналог useEffect", "Хук для работы с DOM"],
    answer: 1,
    explanation: "useCallback(fn, deps) возвращает мемоизированную функцию. Полезен при передаче коллбэков дочерним компонентам, обёрнутым в React.memo.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Чем useMemo отличается от useCallback?",
    options: ["Нет разницы", "useMemo мемоизирует результат вычисления, useCallback — саму функцию", "useCallback работает асинхронно", "useMemo только для строк"],
    answer: 1,
    explanation: "useMemo(() => heavyCalc(), [deps]) — кэшируем значение. useCallback(() => fn, [deps]) — кэшируем функцию. useCallback(fn,d) === useMemo(()=>fn,d).",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое useRef в React?",
    options: ["Хук для ссылок на внешние ресурсы", "Создаёт изменяемый объект {current}, не вызывающий ре-рендер при изменении", "Аналог useState", "Хук для маршрутизации"],
    answer: 1,
    explanation: "useRef используется для: 1) ссылок на DOM-элементы, 2) хранения значений между рендерами без ре-рендера (как instance variable).",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое useContext?",
    options: ["Хук для хранения контекста приложения в localStorage", "Подписывается на React Context и возвращает его текущее значение", "Создаёт глобальное состояние", "Тип пропсов"],
    answer: 1,
    explanation: "useContext(MyContext) — альтернатива Consumer. При изменении провайдера все подписанные компоненты перерендериваются.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое useReducer?",
    options: ["Аналог Array.reduce", "Хук для управления сложным state через чистую функцию-редьюсер (state, action) => newState", "Хук для запросов", "Замена Redux"],
    answer: 1,
    explanation: "Альтернатива useState для сложной логики: const [state, dispatch] = useReducer(reducer, initial). Dispatch отправляет actions.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое React.memo?",
    options: ["Хук для мемоизации", "HOC, предотвращающий ре-рендер компонента если его пропсы не изменились", "Встроенный state менеджер", "Тип компонента"],
    answer: 1,
    explanation: "React.memo делает поверхностное сравнение пропсов. Если не изменились — пропускает рендер. Не помогает если пропсы — новые объекты/функции каждый раз.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое reconciliation в React?",
    options: ["Синхронизация данных с сервером", "Алгоритм сравнения Virtual DOM деревьев для минимальных обновлений реального DOM", "Управление состоянием", "Обработка ошибок"],
    answer: 1,
    explanation: "React сравнивает новый и старый Virtual DOM (diffing), находит минимальный набор изменений и применяет их к реальному DOM.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое key в списках React?",
    options: ["CSS-свойство", "Уникальный идентификатор для элементов списка, помогающий React эффективно обновлять DOM", "Атрибут для анимации", "ID в базе данных"],
    answer: 1,
    explanation: "key помогает React отслеживать какие элементы изменились/добавились/удалились. Должен быть стабильным и уникальным среди соседей.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое Error Boundary в React?",
    options: ["Граница между компонентами", "Классовый компонент, перехватывающий ошибки рендеринга в дочерних компонентах", "Тип обработчика ошибок", "Хук для try/catch"],
    answer: 1,
    explanation: "Error Boundary реализуется через componentDidCatch и getDerivedStateFromError. Показывает fallback UI вместо краша всего приложения.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое React Suspense?",
    options: ["Хук для задержки", "Механизм для отображения fallback UI пока компонент ожидает данные или загружается lazy-компонент", "Тип анимации", "Менеджер состояния"],
    answer: 1,
    explanation: "<Suspense fallback={<Spinner/>}><LazyComponent/></Suspense> — показывает Spinner пока LazyComponent загружается.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое React.lazy()?",
    options: ["Ленивая инициализация state", "Динамический импорт компонента для code splitting", "Оптимизация хуков", "Тип компонента"],
    answer: 1,
    explanation: "const LazyComp = React.lazy(() => import('./Comp')). Компонент загружается только при первом рендере, уменьшая начальный бандл.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое Portals в React?",
    options: ["Ссылки между компонентами", "Механизм рендеринга компонента в DOM-узел вне родительского дерева", "Тип контекста", "Способ передачи пропсов"],
    answer: 1,
    explanation: "ReactDOM.createPortal(child, container) рендерит child в container (например, document.body). Используется для модалок, тостов, tooltip.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое forwardRef в React?",
    options: ["Пересылка пропсов", "Механизм передачи ref через компонент к DOM-элементу внутри него", "Тип хука", "Метод контекста"],
    answer: 1,
    explanation: "forwardRef позволяет родителю получить доступ к DOM-элементу внутри дочернего компонента через ref.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое HOC (Higher-Order Component)?",
    options: ["Компонент высокого разрешения", "Функция, принимающая компонент и возвращающая новый компонент с дополнительным поведением", "Тип хука", "Родительский компонент"],
    answer: 1,
    explanation: "HOC — паттерн для переиспользования логики: withAuth(Component), withTheme(Component). Популярен до хуков, сейчас заменяется кастомными хуками.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое render props?",
    options: ["Свойства для рендеринга", "Паттерн передачи функции рендеринга через проп для переиспользования логики", "Тип пропсов", "Метод компонента"],
    answer: 1,
    explanation: "<DataProvider render={data => <Component data={data}/>}/> — компонент вызывает render-проп для отображения. Предшественник хуков.",
  },

  // ── Браузер ───────────────────────────────────────────────────────────────
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое DOM?",
    options: ["Язык программирования", "Document Object Model — объектное представление HTML-документа в памяти браузера", "CSS-парсер", "Тип базы данных"],
    answer: 1,
    explanation: "DOM — дерево объектов (nodes), отражающее HTML. JavaScript может читать и изменять его через document.querySelector, createElement и т.д.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое repaint и reflow браузера?",
    options: ["Типы анимаций", "Reflow — пересчёт геометрии (layout), repaint — перерисовка пикселей без изменения геометрии", "Шаги парсинга HTML", "Оптимизации рендера"],
    answer: 1,
    explanation: "Reflow дороже repaint: изменение ширины вызывает reflow всего дерева. transform и opacity вызывают только compositing — самое дешёвое.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое Critical Rendering Path?",
    options: ["Путь к главной странице", "Последовательность шагов браузера от HTML до пикселей: HTML→DOM, CSS→CSSOM, render tree, layout, paint", "Критические ошибки рендеринга", "Метрика производительности"],
    answer: 1,
    explanation: "Оптимизация CRP: минимизировать блокирующие ресурсы, инлайнить критический CSS, откладывать некритические скрипты (async/defer).",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое requestAnimationFrame?",
    options: ["Функция для загрузки изображений", "API для запуска кода перед следующей перерисовкой браузера (~60 раз/сек)", "Таймер с задержкой 16мс", "Метод canvas"],
    answer: 1,
    explanation: "rAF синхронизируется с частотой экрана. Используй вместо setInterval для анимаций — это плавнее и эффективнее.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое IntersectionObserver?",
    options: ["Наблюдатель за пересечениями CSS", "API для отслеживания попадания элемента в область видимости (viewport)", "Метод для позиционирования", "Тип события"],
    answer: 1,
    explanation: "IntersectionObserver используется для: lazy loading изображений, infinite scroll, анимации при появлении элемента — без scroll event listener.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое MutationObserver?",
    options: ["Наблюдатель за мутациями CSS", "API для отслеживания изменений в DOM-дереве", "Аналог IntersectionObserver", "Метод работы с формами"],
    answer: 1,
    explanation: "MutationObserver следит за добавлением/удалением узлов, изменением атрибутов и т.д. Используется в полифиллах и библиотеках.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое Web Workers?",
    options: ["Сервисные работники сайта", "Скрипты, выполняющиеся в фоновом потоке отдельно от основного UI-потока", "Веб-серверы", "Service Workers"],
    answer: 1,
    explanation: "Web Workers позволяют выполнять тяжёлые вычисления без блокировки UI. Общаются с основным потоком через postMessage.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое Service Worker?",
    options: ["Web Worker для API-запросов", "Скрипт, работающий как прокси между браузером и сетью, обеспечивающий офлайн-режим и кэш", "Воркер для DOM-операций", "Серверный скрипт"],
    answer: 1,
    explanation: "Service Worker — основа PWA. Перехватывает fetch-запросы, управляет кэшем, отправляет push-уведомления. Работает даже без вкладки.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое IndexedDB?",
    options: ["SQL-база в браузере", "Низкоуровневое NoSQL-хранилище браузера для больших объёмов структурированных данных", "Аналог localStorage", "Серверная БД"],
    answer: 1,
    explanation: "IndexedDB асинхронный, поддерживает транзакции, индексы, хранит любые объекты. localStorage синхронный и только строки.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое cache-control: no-store?",
    options: ["Кэшировать навсегда", "Запрет любого кэширования — каждый раз загружать с сервера", "Проверять кэш раз в день", "Кэшировать только в памяти"],
    answer: 1,
    explanation: "no-store полностью отключает кэш. no-cache — разрешает хранить, но требует валидацию. max-age=31536000 — кэшировать год.",
  },

  // ── Производительность и оптимизация ──────────────────────────────────────
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое Core Web Vitals?",
    options: ["CSS-переменные", "Метрики Google для оценки UX: LCP, FID/INP, CLS", "Браузерные API", "Типы HTTP-запросов"],
    answer: 1,
    explanation: "LCP (загрузка), INP (интерактивность), CLS (стабильность лейаута) — ключевые метрики, влияющие на SEO в Google.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое LCP (Largest Contentful Paint)?",
    options: ["Размер самого большого изображения", "Время до отображения самого большого видимого элемента (цель: <2.5с)", "Количество элементов DOM", "Тип оптимизации"],
    answer: 1,
    explanation: "LCP измеряет воспринимаемую скорость загрузки. Улучшается: оптимизацией изображений, CDN, preload критических ресурсов.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое CLS (Cumulative Layout Shift)?",
    options: ["Количество перерисовок", "Метрика смещения элементов страницы во время загрузки (цель: <0.1)", "Скорость CSS-парсинга", "Тип анимации"],
    answer: 1,
    explanation: "CLS страдает когда шрифты/изображения подгружаются и толкают контент. Решение: задавать размеры заранее, font-display: optional.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое code splitting?",
    options: ["Разделение кода по файлам", "Разбиение бандла на части, загружаемые по мере необходимости", "Минификация кода", "Обфускация кода"],
    answer: 1,
    explanation: "Code splitting (React.lazy, dynamic import) уменьшает начальный бандл. Пользователь загружает только нужный код, остальное — по требованию.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое tree shaking?",
    options: ["Анимация трясущегося дерева", "Удаление неиспользуемого кода из бандла на этапе сборки", "Очистка DOM", "Тип рефакторинга"],
    answer: 1,
    explanation: "Tree shaking работает с ES-модулями (import/export). Bundler (Webpack, Rollup) анализирует что используется и выбрасывает лишнее.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое lazy loading изображений?",
    options: ["Медленная загрузка", "Откладывание загрузки изображений до момента их приближения к viewport", "Кэширование изображений", "Сжатие изображений"],
    answer: 1,
    explanation: "<img loading='lazy'> — нативный lazy loading. Изображение загружается только когда пользователь прокручивает к нему.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое preload в HTML?",
    options: ["Предзагрузка страницы", "<link rel='preload'> — указывает браузеру загрузить ресурс с высоким приоритетом как можно раньше", "Кэширование ресурса", "Предзагрузка скрипта"],
    answer: 1,
    explanation: "<link rel='preload' href='font.woff2' as='font'> — критичные ресурсы грузятся раньше. Не используй для всего — это снизит приоритет важного.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое Content Security Policy (CSP)?",
    options: ["Политика контента компании", "HTTP-заголовок, ограничивающий источники загрузки ресурсов для защиты от XSS", "Тип кэша", "Настройка сервера"],
    answer: 1,
    explanation: "CSP: Content-Security-Policy: default-src 'self' запрещает загрузку ресурсов с других доменов. Мощная защита от XSS.",
  },

  // ── Безопасность ──────────────────────────────────────────────────────────
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое XSS (Cross-Site Scripting)?",
    options: ["Тип CSS-атаки", "Внедрение вредоносного JavaScript в страницу через пользовательский ввод", "Атака на сервер", "Тип SQL-инъекции"],
    answer: 1,
    explanation: "XSS: злоумышленник внедряет скрипт, который выполняется в браузере жертвы. Защита: экранирование вывода, CSP, HttpOnly cookies.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое CSRF (Cross-Site Request Forgery)?",
    options: ["Тип XSS-атаки", "Атака, заставляющая браузер жертвы выполнить нежелательный запрос к сайту, где она авторизована", "SQL-инъекция", "Атака на DNS"],
    answer: 1,
    explanation: "CSRF использует куки браузера. Защита: CSRF-токены, SameSite=Strict для кук, проверка Origin/Referer заголовков.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое HTTPS и TLS?",
    options: ["Новая версия HTTP", "TLS — протокол шифрования; HTTPS = HTTP поверх TLS для защищённой передачи данных", "Тип авторизации", "Протокол WebSocket"],
    answer: 1,
    explanation: "TLS (ранее SSL) шифрует трафик, аутентифицирует сервер, обеспечивает целостность данных. Без HTTPS — куки и данные видны посредникам.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое Same-Origin Policy?",
    options: ["Политика единого кода", "Браузерное ограничение: скрипт с одного origin не может читать данные с другого", "Тип CORS", "Политика кэширования"],
    answer: 1,
    explanation: "Origin = схема + домен + порт. https://a.com не может читать ответ от https://b.com без CORS-заголовков на сервере.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что делает атрибут HttpOnly у cookie?",
    options: ["Cookie только для HTTP-сайтов", "Запрещает доступ к cookie через JavaScript (document.cookie), защищая от XSS", "Шифрует cookie", "Ограничивает срок жизни"],
    answer: 1,
    explanation: "HttpOnly cookie недоступны через JS. Даже если XSS внедрился, он не сможет украсть такую cookie. Всегда используй для session tokens.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое Subresource Integrity (SRI)?",
    options: ["Тип SSL", "Механизм проверки что загруженный ресурс не был изменён — через хэш в атрибуте integrity", "Подпись сертификата", "Метод шифрования"],
    answer: 1,
    explanation: "<script src='...' integrity='sha384-...' crossorigin='anonymous'> — браузер проверяет хэш файла. Защита от CDN-компрометации.",
  },

  // ── HTTP и сеть ───────────────────────────────────────────────────────────
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "В чём разница между GET и POST?",
    options: ["Нет разницы", "GET получает данные (параметры в URL, кэшируется); POST отправляет данные (в теле, не кэшируется)", "POST быстрее", "GET только для форм"],
    answer: 1,
    explanation: "GET — идемпотентный, безопасный. POST — для создания/изменения данных. Параметры GET в URL, POST в body.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое HTTP/2 и чем он отличается от HTTP/1.1?",
    options: ["Новое название HTTP", "Бинарный протокол с мультиплексингом, сжатием заголовков и server push", "HTTP для мобильных", "Зашифрованный HTTP"],
    answer: 1,
    explanation: "HTTP/2: одно TCP-соединение для множества запросов (мультиплексинг). HTTP/1.1 ограничен ~6 параллельными соединениями на домен.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое preflight-запрос в CORS?",
    options: ["Первый запрос к серверу", "OPTIONS-запрос, отправляемый браузером перед 'сложным' кросс-доменным запросом для проверки разрешений", "Запрос с авторизацией", "Кэшированный запрос"],
    answer: 1,
    explanation: "Браузер отправляет OPTIONS с заголовками Origin, Access-Control-Request-Method. Сервер отвечает что разрешено. Только потом — реальный запрос.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое fetch API?",
    options: ["jQuery-метод", "Современный браузерный API для HTTP-запросов на основе Promise", "Аналог XMLHttpRequest без промисов", "Node.js-модуль"],
    answer: 1,
    explanation: "fetch() возвращает Promise<Response>. Важно: fetch не отклоняет промис при 4xx/5xx — только при сетевой ошибке. Проверяй response.ok.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Чем axios отличается от fetch?",
    options: ["Нет разницы", "axios автоматически парсит JSON, отклоняет промис при ошибках HTTP, работает в Node.js и браузере, поддерживает interceptors", "fetch быстрее axios", "axios только для POST"],
    answer: 1,
    explanation: "axios удобнее из коробки: авто-парсинг JSON, таймауты, cancel tokens, interceptors. fetch нативный, но требует больше кода.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое REST vs GraphQL?",
    options: ["Оба одинаковы", "REST: фиксированные эндпоинты для ресурсов; GraphQL: один эндпоинт, клиент запрашивает точно нужные данные", "GraphQL только для мобильных", "REST быстрее"],
    answer: 1,
    explanation: "REST: overfetching (лишние данные) и underfetching (несколько запросов). GraphQL решает это: клиент описывает нужную форму данных.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое WebRTC?",
    options: ["Протокол для веб-серверов", "API для прямой peer-to-peer связи между браузерами (видео, аудио, данные)", "Тип WebSocket", "Протокол шифрования"],
    answer: 1,
    explanation: "WebRTC позволяет браузерам общаться напрямую без сервера-посредника. Основа видеозвонков (Google Meet, Zoom в браузере).",
  },

  // ── Инструменты и экосистема ──────────────────────────────────────────────
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое Webpack?",
    options: ["Тестовый фреймворк", "Модульный бандлер: собирает JS, CSS, картинки в один (или несколько) файл(ов)", "Линтер", "Менеджер пакетов"],
    answer: 1,
    explanation: "Webpack анализирует граф зависимостей от entry point, применяет loaders для трансформации файлов и plugins для оптимизации.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое Vite?",
    options: ["Аналог Webpack", "Сборщик нового поколения: в dev использует ESM без бандлинга, в prod — Rollup", "Тестовый фреймворк", "CSS-фреймворк"],
    answer: 1,
    explanation: "Vite (фр. 'быстро') — dev-сервер без бандлинга: отдаёт ESM напрямую браузеру. Намного быстрее Webpack при разработке.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое ESLint?",
    options: ["ES6 линейки", "Статический анализатор JavaScript, находящий ошибки и нарушения стиля кода", "Компилятор TypeScript", "Минификатор"],
    answer: 1,
    explanation: "ESLint анализирует AST кода и применяет правила. Поддерживает плагины (react, typescript, prettier). Интегрируется в CI.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое Prettier?",
    options: ["Линтер кода", "Инструмент автоформатирования кода с минимальными настройками", "Компилятор CSS", "Менеджер пакетов"],
    answer: 1,
    explanation: "Prettier форматирует код детерминированно: убирает дискуссии о стиле. В отличие от ESLint, не ищет ошибки — только форматирует.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое Babel?",
    options: ["Переводчик языков", "JavaScript транспилер: преобразует современный JS/JSX в код, поддерживаемый старыми браузерами", "CSS-препроцессор", "Тестовый фреймворк"],
    answer: 1,
    explanation: "Babel с пресетами (@babel/preset-env, @babel/preset-react) транспилирует ES2022+ и JSX в ES5. В 2024 чаще заменяется SWC/esbuild.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое npm vs yarn vs pnpm?",
    options: ["Одно и то же", "Менеджеры пакетов Node.js; yarn добавил lockfile и workspace; pnpm экономит дисковое место через hardlinks", "Системы сборки", "Форматы пакетов"],
    answer: 1,
    explanation: "npm — стандарт. yarn — параллельная установка, workspaces. pnpm — самый быстрый и экономичный: пакеты хранятся один раз в глобальном store.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое Storybook?",
    options: ["Менеджер задач", "Инструмент для разработки UI-компонентов в изоляции с документацией", "Тестовый раннер", "CSS-фреймворк"],
    answer: 1,
    explanation: "Storybook позволяет разрабатывать компоненты в изоляции, видеть все состояния, автоматически документировать API и делать visual testing.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое Jest?",
    options: ["CSS-фреймворк", "Тестовый фреймворк для JavaScript с встроенными матчерами, моками и покрытием", "Линтер", "Бандлер"],
    answer: 1,
    explanation: "Jest — стандарт юнит-тестирования в экосистеме React. Встроенный jsdom, mock functions, snapshot testing, coverage из коробки.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое Testing Library?",
    options: ["Библиотека тестовых данных", "Утилиты для тестирования компонентов с позиции пользователя (не деталей реализации)", "Стресс-тестирование", "E2E-тестирование"],
    answer: 1,
    explanation: "getByRole, getByText — Testing Library поощряет тесты, проверяющие что видит пользователь, а не внутренние состояния.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое Cypress?",
    options: ["CSS-препроцессор", "E2E-тестовый фреймворк для тестирования приложения в реальном браузере", "Юнит-тестирование", "Линтер"],
    answer: 1,
    explanation: "Cypress запускает тесты прямо в браузере, имеет time-travel debugging, автоснимки, перехват сетевых запросов. Конкурент Playwright.",
  },

  // ── Доступность (a11y) ────────────────────────────────────────────────────
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое ARIA в контексте веб-доступности?",
    options: ["Язык разметки", "Accessible Rich Internet Applications — атрибуты для улучшения доступности динамического контента", "Тип анимации", "Стандарт CSS"],
    answer: 1,
    explanation: "aria-label, aria-hidden, role='button' — ARIA добавляет семантику для скринридеров там, где нативных HTML-тегов недостаточно.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое WCAG?",
    options: ["CSS-стандарт", "Web Content Accessibility Guidelines — международные стандарты доступности (уровни A, AA, AAA)", "Протокол браузера", "Формат шрифта"],
    answer: 1,
    explanation: "WCAG 2.1 AA — минимальный стандарт для большинства сайтов. Включает: контрастность, keyboard navigation, альтернативный текст.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Почему важен порядок фокуса (focus order) на странице?",
    options: ["Для SEO", "Пользователи клавиатуры и скринридеров навигируют по Tab — логичный порядок фокуса критичен для доступности", "Для анимации", "Для производительности"],
    answer: 1,
    explanation: "Focus order должен совпадать с визуальным порядком. Не используй tabindex > 0. Всегда показывай :focus стили — не убирай outline без замены.",
  },

  // ── Состояние и архитектура ───────────────────────────────────────────────
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое Redux?",
    options: ["React-роутер", "Предсказуемый контейнер состояния с единым store, actions и reducers", "CSS-фреймворк", "Тип API"],
    answer: 1,
    explanation: "Redux: единый store, state только через dispatch(action), reducers — чистые функции. Паттерн Flux. Сейчас часто заменяется Zustand/Jotai.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое Flux-архитектура?",
    options: ["CSS-методология", "Однонаправленный поток данных: Action → Dispatcher → Store → View", "Тип API", "Паттерн серверного рендеринга"],
    answer: 1,
    explanation: "Flux предложен Facebook как альтернатива MVC. Redux — реализация Flux с одним store. Данные текут в одном направлении — предсказуемость.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое React Query (TanStack Query)?",
    options: ["SQL для React", "Библиотека для управления серверным состоянием: кэшинг, фоновое обновление, дедупликация запросов", "Аналог Redux", "Тип хука"],
    answer: 1,
    explanation: "React Query разделяет серверное и клиентское состояние. Автоматически кэширует, обновляет в фоне, обрабатывает loading/error состояния.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое Zustand?",
    options: ["Немецкий фреймворк", "Минималистичная библиотека состояния для React без бойлерплейта Redux", "Менеджер пакетов", "CSS-методология"],
    answer: 1,
    explanation: "Zustand: create(set => ({count: 0, inc: () => set(s => ({count: s.count+1}))})) — весь store в 5 строк. Популярная альтернатива Redux.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое атомарное состояние (Jotai, Recoil)?",
    options: ["Минимальное состояние", "Подход где состояние разбито на мелкие независимые атомы, компоненты подписываются только на нужные", "Глобальный store", "Тип хука"],
    answer: 1,
    explanation: "Атомы — маленькие единицы состояния. Компонент перерендеривается только при изменении нужного атома. Гибче Redux, проще React Context.",
  },

  // ── Next.js и SSR ──────────────────────────────────────────────────────────
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое Next.js?",
    options: ["Альтернатива React", "React-фреймворк с SSR, SSG, file-based routing и API routes из коробки", "Серверный фреймворк без React", "Менеджер пакетов"],
    answer: 1,
    explanation: "Next.js добавляет к React: SSR/SSG, маршрутизацию по файловой системе, Image/Link оптимизации, API routes, Middleware.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое SSG (Static Site Generation)?",
    options: ["Рендеринг на клиенте", "Генерация HTML на этапе сборки — страницы готовы заранее и отдаются мгновенно с CDN", "Рендеринг на сервере при каждом запросе", "Гибридный рендеринг"],
    answer: 1,
    explanation: "SSG: быстрее всего (CDN), отлично для SEO. Минус: нельзя показывать персональные данные, нужна пересборка при изменении контента.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое ISR (Incremental Static Regeneration) в Next.js?",
    options: ["Постепенная загрузка стилей", "Регенерация статических страниц в фоне через заданный интервал без полной пересборки", "Тип code splitting", "Оптимизация изображений"],
    answer: 1,
    explanation: "ISR: revalidate: 60 — страница статическая, но обновляется каждые 60 секунд в фоне. Золотая середина между SSR и SSG.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое hydration в контексте SSR?",
    options: ["Добавление воды в код", "Процесс присоединения React к уже готовому HTML от сервера для добавления интерактивности", "Загрузка данных", "Кэширование страниц"],
    answer: 1,
    explanation: "Сервер отдаёт статический HTML (быстрый FCP), затем React 'гидратирует' его — вешает обработчики, восстанавливает состояние.",
  },

  // ── CSS-архитектура и методологии ─────────────────────────────────────────
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое BEM в CSS?",
    options: ["CSS-фреймворк", "Методология именования классов: Блок__Элемент--Модификатор", "Тип селектора", "Препроцессор"],
    answer: 1,
    explanation: ".card__title--highlighted — BEM делает CSS предсказуемым и избегает конфликтов. Многословно, но структурировано.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое Tailwind CSS?",
    options: ["CSS-фреймворк с готовыми компонентами", "Utility-first CSS: классы-утилиты (flex, p-4, text-sm) прямо в HTML вместо написания CSS", "Аналог Bootstrap", "CSS-препроцессор"],
    answer: 1,
    explanation: "Tailwind: flex items-center gap-4 p-2 в HTML вместо CSS-файла. Быстрое прототипирование, нет конфликтов. Вопрос вкуса — код в HTML vs CSS.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое CSS-in-JS?",
    options: ["Инлайн-стили", "Подход написания CSS прямо в JavaScript (styled-components, Emotion) с динамическими стилями", "CSS в JSON", "Тип CSS-модулей"],
    answer: 1,
    explanation: "styled-components: const Button = styled.button`background: ${props => props.primary ? 'blue' : 'white'}`. Динамика + инкапсуляция.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое атомарный CSS?",
    options: ["CSS для маленьких элементов", "Подход где каждый класс делает одно (одно свойство): .flex { display: flex }. Основа Tailwind и Atomic CSS", "CSS-методология для команд", "Тип препроцессора"],
    answer: 1,
    explanation: "Атомарный CSS минимизирует размер: классы переиспользуются. Цена — много классов в HTML. Tailwind — самый популярный пример.",
  },

  // ── Vue и другие фреймворки ────────────────────────────────────────────────
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое Vue.js?",
    options: ["Альтернатива JavaScript", "Прогрессивный фреймворк для построения UI с реактивной системой на основе Proxy", "Серверный фреймворк", "CSS-библиотека"],
    answer: 1,
    explanation: "Vue — прогрессивный: можно добавить к существующему сайту или строить SPA. Реактивность через Proxy (Vue 3), шаблоны, Composition API.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое реактивность в Vue?",
    options: ["Быстрый отклик UI", "Система автоматического отслеживания зависимостей: при изменении данных View обновляется само", "Тип анимации", "Метод жизненного цикла"],
    answer: 1,
    explanation: "Vue 3 оборачивает данные в Proxy. При чтении — собирает зависимости, при записи — уведомляет подписчиков. Полностью автоматически.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое Angular?",
    options: ["Библиотека для DOM", "Полноценный фреймворк Google с TypeScript, DI, RxJS, модулями и мощным CLI", "Альтернатива React без виртуального DOM", "CSS-фреймворк"],
    answer: 1,
    explanation: "Angular — opinionated full framework: всё включено. RxJS для асинхронности, DI из коробки, строгий TypeScript. Крупные enterprise-проекты.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое Svelte?",
    options: ["CSS-фреймворк", "Компилируемый фреймворк: компонентный код компилируется в чистый JS без runtime", "Аналог Vue", "Node.js-фреймворк"],
    answer: 1,
    explanation: "Svelte не использует Virtual DOM. Компилятор генерирует хирургически точный код обновления DOM. Минимальный размер бандла.",
  },

  // ── Паттерны и архитектура ─────────────────────────────────────────────────
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое MVC в контексте фронтенда?",
    options: ["Тип API", "Model-View-Controller: разделение данных, отображения и логики управления", "Тип CSS", "Паттерн работы с сервером"],
    answer: 1,
    explanation: "MVC на фронте: Model — данные/state, View — UI (React компоненты), Controller — обработчики событий, обновляющие Model.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое Container/Presentational Components паттерн?",
    options: ["Тип HOC", "Разделение: контейнеры управляют данными, презентационные — только отображают пропсы", "Тип роутинга", "CSS-методология"],
    answer: 1,
    explanation: "Умные (container) компоненты — fetching, state. Глупые (presentational) — только UI по пропсам. Переиспользуемость и тестируемость.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое Feature-Sliced Design (FSD)?",
    options: ["Метод нарезки изображений", "Архитектурная методология для фронтенд-проектов: слои, фичи, сущности, shared", "Паттерн компонентов", "Тип роутинга"],
    answer: 1,
    explanation: "FSD: app → pages → widgets → features → entities → shared. Строгая изоляция слоёв, правила импортов. Популярно в enterprise React-проектах.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое Micro Frontends?",
    options: ["Маленькие React-компоненты", "Архитектурный подход: фронтенд разбит на независимые части, разрабатываемые разными командами", "CSS-методология", "Тип тестирования"],
    answer: 1,
    explanation: "Micro Frontends — фронтенд-аналог микросервисов. Каждая команда владеет своим куском UI. Module Federation (Webpack 5) — популярная реализация.",
  },

  // ── Анимации и Canvas ─────────────────────────────────────────────────────
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое CSS-transitions?",
    options: ["Тип анимации для SVG", "Плавное изменение CSS-свойства от одного значения к другому за заданное время", "JavaScript-анимации", "Анимации через requestAnimationFrame"],
    answer: 1,
    explanation: "transition: color 0.3s ease — при изменении color класса анимирует переход. Проще чем @keyframes, для простых состояний.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое @keyframes?",
    options: ["Ключевые кадры видео", "CSS-правило для создания сложных многошаговых анимаций с промежуточными состояниями", "Тип медиазапроса", "SVG-анимация"],
    answer: 1,
    explanation: "@keyframes spin { from {transform: rotate(0)} to {transform: rotate(360deg)} } — затем animation: spin 1s linear infinite.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Чем лучше анимировать: transform/opacity или width/margin?",
    options: ["Нет разницы", "transform и opacity — только compositing (GPU), width/margin вызывают reflow и дороги", "width быстрее", "margin анимируется плавнее"],
    answer: 1,
    explanation: "transform и opacity не вызывают layout или paint — браузер переносит их на GPU. width, height, margin — reflow всего дерева.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое Canvas API?",
    options: ["HTML-тег для картинок", "API для попиксельного рисования 2D-графики через JavaScript", "CSS-свойство", "SVG-метод"],
    answer: 1,
    explanation: "<canvas> + getContext('2d') позволяет рисовать фигуры, изображения, текст. Используется для игр, визуализаций, редакторов изображений.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Чем SVG отличается от Canvas?",
    options: ["Нет разницы", "SVG — векторный, декларативный, доступный, масштабируется без потерь; Canvas — растровый, попиксельный, нет DOM-элементов", "Canvas лучше для иконок", "SVG только для анимаций"],
    answer: 1,
    explanation: "SVG: иконки, диаграммы, интерактивность через DOM-события. Canvas: игры, видеообработка, тысячи объектов — где DOM был бы слишком медленным.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое Web Animations API?",
    options: ["jQuery animate()", "Нативный JS API для создания анимаций: element.animate([{opacity:0},{opacity:1}], {duration:300})", "CSS @keyframes в JS", "Тип requestAnimationFrame"],
    answer: 1,
    explanation: "WAAPI — нативная альтернатива CSS-анимациям через JS. Поддерживает управление (play, pause, reverse), промисы завершения.",
  },

  // ── PWA и мобильный веб ───────────────────────────────────────────────────
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое PWA (Progressive Web App)?",
    options: ["Нативное мобильное приложение", "Веб-приложение, использующее Service Workers и Manifest для офлайн-работы и установки на устройство", "Тип SPA", "React Native"],
    answer: 1,
    explanation: "PWA: устанавливается как приложение, работает офлайн, получает push-уведомления. Одна кодовая база для web и 'нативного' опыта.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое Web App Manifest?",
    options: ["Список зависимостей", "JSON-файл, описывающий PWA: имя, иконки, цвета, режим отображения для установки на устройство", "Service Worker конфиг", "manifest.json в Webpack"],
    answer: 1,
    explanation: "manifest.json с name, icons, start_url, display: 'standalone' позволяет браузеру предложить установку PWA и запускать его без UI браузера.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое viewport meta-тег?",
    options: ["Тег для SEO", "<meta name='viewport' content='width=device-width, initial-scale=1'> — управляет масштабированием на мобильных устройствах", "Тег для мета-описания", "Тег для иконки"],
    answer: 1,
    explanation: "Без viewport браузер масштабирует страницу как десктоп. width=device-width делает ширину равной экрану устройства — основа адаптивной вёрстки.",
  },

  // ── Интернационализация ───────────────────────────────────────────────────
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое i18n?",
    options: ["18-й стандарт HTML", "Интернационализация (internationalization) — адаптация приложения для разных языков и локалей", "Тип API", "CSS-методология"],
    answer: 1,
    explanation: "i18n (18 букв между i и n). Включает: переводы, форматирование дат/чисел, RTL-языки, множественные формы. Библиотеки: i18next, react-intl.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое атрибут lang в HTML?",
    options: ["Язык программирования", "<html lang='ru'> — сообщает браузеру и скринридеру язык страницы для правильного произношения и автоперевода", "Атрибут для форм", "Метатег SEO"],
    answer: 1,
    explanation: "lang важен для доступности: скринридер выбирает правильное произношение. Поисковики используют для геотаргетинга.",
  },

  // ── Разное / продвинутое ──────────────────────────────────────────────────
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое Monorepo?",
    options: ["Один большой файл", "Хранение нескольких проектов/пакетов в одном репозитории", "Тип архитектуры API", "Один компонент для всего"],
    answer: 1,
    explanation: "Monorepo: единый репозиторий для frontend, backend, shared-библиотек. Инструменты: Turborepo, Nx, pnpm workspaces. Упрощает рефакторинг и переиспользование.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое Module Federation в Webpack 5?",
    options: ["Объединение модулей", "Механизм для загрузки кода из другого приложения во время выполнения — основа Micro Frontends", "Тип code splitting", "Оптимизация бандла"],
    answer: 1,
    explanation: "Module Federation позволяет приложению A использовать компоненты из приложения B в рантайме без установки пакетов. Ключевая технология MFE.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое тип контента application/json в HTTP?",
    options: ["Тип файловой системы", "Content-Type заголовок, указывающий что тело запроса/ответа — JSON", "Тип авторизации", "Формат куки"],
    answer: 1,
    explanation: "Content-Type: application/json говорит серверу как парсить тело. Без него многие серверы не поймут данные. fetch нужно указывать явно.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое декораторы (decorators) в TypeScript/JavaScript?",
    options: ["Тип комментариев", "@декораторы — функции, модифицирующие классы, методы или свойства на этапе объявления", "Тип импорта", "CSS-анимации"],
    answer: 1,
    explanation: "@Injectable(), @Component() — декораторы популярны в Angular и NestJS. TC39 Stage 3, TypeScript поддерживает через experimentalDecorators.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое изоморфный (universal) JavaScript?",
    options: ["Кроссбраузерный JS", "Код, работающий и на сервере (Node.js), и в браузере без изменений", "Стандарт ES2020", "Тип тестирования"],
    answer: 1,
    explanation: "Изоморфный код: рендеринг на сервере для SEO + hydration на клиенте для интерактивности. Основа Next.js, Nuxt.js.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое абстракция leaky abstraction?",
    options: ["Утечка памяти в абстракции", "Абстракция, которая 'протекает' — скрывает детали реализации, но они всё равно влияют на поведение", "Тип архитектурной ошибки", "Антипаттерн в CSS"],
    answer: 1,
    explanation: "Закон Джоэля Сполски: все нетривиальные абстракции протекают. SQL ORM скрывает запросы, но N+1 проблема всё равно появляется.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое Progressive Enhancement?",
    options: ["Постепенная загрузка", "Подход: сначала базовый функционал для всех (HTML), затем улучшения для современных браузеров (CSS, JS)", "Тип тестирования", "Метод оптимизации"],
    answer: 1,
    explanation: "PE: страница работает без JS (базово), CSS делает красивее, JS добавляет интерактивность. Противоположность: Graceful Degradation.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое Web Components?",
    options: ["React-компоненты", "Нативные браузерные стандарты для создания переиспользуемых компонентов: Custom Elements, Shadow DOM, HTML Templates", "Vue-компоненты", "npm-пакеты"],
    answer: 1,
    explanation: "Web Components работают в любом фреймворке или без него. <my-button> — кастомный элемент с инкапсулированными стилями в Shadow DOM.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое FLIP-анимации?",
    options: ["Тип CSS-трансформации", "Техника: First-Last-Invert-Play для плавных анимаций с измерением начального и конечного положения", "Анимации для мобильных", "jQuery-плагин"],
    answer: 1,
    explanation: "FLIP: снять First позицию → выполнить изменение → снять Last → Invert через transform → Play анимацию. Дёшево (только compositing).",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое Temporal Dead Zone (TDZ) в JavaScript?",
    options: ["Зона без таймеров", "Период между началом блока и объявлением let/const, когда обращение к переменной вызывает ReferenceError", "Область без this", "Зона вне модуля"],
    answer: 1,
    explanation: "let x = 1; — до этой строки x в TDZ. В отличие от var (undefined при hoisting), let/const бросают ReferenceError в TDZ.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое tree shaking и почему ES-модули важны для него?",
    options: ["ES-модули не важны", "ES-модули статически анализируемы — бандлер знает импорты/экспорты до выполнения, позволяя удалить неиспользуемый код", "CommonJS лучше для tree shaking", "tree shaking работает только в Node.js"],
    answer: 1,
    explanation: "CommonJS require() динамический — бандлер не знает что нужно до выполнения. ES import/export статические — анализ возможен без запуска.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое первоначальный Time to Interactive (TTI)?",
    options: ["Время первого байта", "Время до момента, когда страница становится стабильно интерактивной для пользователя", "Время парсинга HTML", "Время DNS-резолвции"],
    answer: 1,
    explanation: "TTI: страница визуально готова и основные обработчики зарегистрированы. Улучшается: code splitting, defer скриптов, минимизация main thread.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое CSS containment (contain)?",
    options: ["Ограничение размера блока", "CSS-свойство, изолирующее поддерево от остального документа для оптимизации рендеринга", "Тип overflow", "Метод позиционирования"],
    answer: 1,
    explanation: "contain: layout paint — браузер не проверяет влияние элемента на остальной документ. Ускоряет reflow в сложных UI.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое CSS Houdini?",
    options: ["CSS-библиотека", "Набор низкоуровневых браузерных API, дающих доступ к CSS rendering engine через JS", "Имя создателя CSS", "Тип анимации"],
    answer: 1,
    explanation: "Houdini: Paint API, Layout API, Animation Worklet — разработчики могут расширять CSS сами, не ждя стандартов.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое view transitions API?",
    options: ["React Router анимации", "Нативный браузерный API для плавных переходов между состояниями страницы (как в нативных приложениях)", "CSS transitions для роутинга", "jQuery fade"],
    answer: 1,
    explanation: "document.startViewTransition(() => updateDOM()) — браузер снимает скриншоты до/после и анимирует переход. Без JS-анимационных библиотек.",
  },
];

module.exports = webQuestions;
// Дополнительные вопросы до 200

const extraWebQuestions = [
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое CSS логические свойства (margin-inline, padding-block)?",
    options: ["Устаревший синтаксис", "Свойства, адаптирующиеся к направлению текста (LTR/RTL) вместо физических сторон (left/right)", "Тип flexbox", "Медиазапросы"],
    answer: 1,
    explanation: "margin-inline-start вместо margin-left работает корректно для RTL-языков (арабский, иврит) без медиазапросов.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое CSS :is() и :where()?",
    options: ["Устаревшие псевдоклассы", "Псевдоклассы для группировки селекторов; :is() сохраняет специфичность, :where() — всегда 0", "Только для Chrome", "Аналоги @media"],
    answer: 1,
    explanation: ":is(h1, h2, h3) a — короче чем h1 a, h2 a, h3 a. :where() то же, но без добавления специфичности.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое CSS container queries?",
    options: ["Медиазапросы для контейнера", "Запросы, применяющие стили в зависимости от размера родительского контейнера, а не viewport", "Тип grid", "Вложенные медиазапросы"],
    answer: 1,
    explanation: "@container (min-width: 400px) { } — компонент меняет стиль в зависимости от своего контейнера, а не экрана. Революция для компонентного CSS.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое структурный клон (structuredClone)?",
    options: ["Метод React", "Нативный браузерный метод глубокого клонирования объектов (включая Map, Set, Date)", "JSON.parse(JSON.stringify())", "Тип spread-оператора"],
    answer: 1,
    explanation: "structuredClone(obj) — нативный глубокий клон, поддерживает Map, Set, Date, ArrayBuffer. Лучше JSON.parse/stringify для сложных объектов.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое temporal API (Temporal) в JavaScript?",
    options: ["Временные переменные", "Новый стандартный API для работы с датами и временем, заменяющий Date", "Тип таймера", "Метод setTimeout"],
    answer: 1,
    explanation: "Temporal (TC39 Stage 3) исправляет проблемы Date: иммутабельность, часовые пояса, человеческий API. Полифилл уже доступен.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое at() метод массива?",
    options: ["Метод поиска", "Метод доступа к элементу по индексу, включая отрицательные: arr.at(-1) === последний элемент", "Тип деструктуризации", "Метод среза"],
    answer: 1,
    explanation: "arr.at(-1) вместо arr[arr.length-1]. Работает для массивов, строк и TypedArray.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое Object.hasOwn()?",
    options: ["Проверка на null", "Статичный метод проверки собственного свойства объекта, более безопасный чем hasOwnProperty", "Тип проверки типа", "Метод прототипа"],
    answer: 1,
    explanation: "Object.hasOwn(obj, 'key') безопаснее obj.hasOwnProperty('key') — работает даже если у объекта нет прототипа (Object.create(null)).",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое pattern matching в CSS (:has())?",
    options: ["Регулярные выражения", ":has() — реляционный псевдокласс: выбирает элемент если у него есть потомок, соответствующий селектору", "Тип медиазапроса", "Только для form-элементов"],
    answer: 1,
    explanation: "a:has(img) — стилизует ссылки с картинкой внутри. article:has(h2) — статьи с заголовком. Первый настоящий 'родительский' селектор в CSS.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое Stale-While-Revalidate (SWR) стратегия кэширования?",
    options: ["Устаревший кэш", "Отдаём кэшированные (stale) данные немедленно, параллельно обновляем в фоне (revalidate)", "Инвалидация кэша", "Тип HTTP-заголовка"],
    answer: 1,
    explanation: "SWR: пользователь сразу видит данные (пусть устаревшие), свежие придут тихо в фоне. Реализовано в библиотеке SWR и React Query.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое Streams API в браузере?",
    options: ["WebRTC потоки", "API для работы с потоковыми данными: ReadableStream, WritableStream, TransformStream", "Audio API", "Тип WebSocket"],
    answer: 1,
    explanation: "Streams позволяют обрабатывать данные по мере получения, не дожидаясь полной загрузки. fetch() возвращает ReadableStream в response.body.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое CSS nesting?",
    options: ["Вложенность HTML", "Нативная вложенность правил в CSS без препроцессоров: .parent { .child { } }", "Тип специфичности", "SASS-функция"],
    answer: 1,
    explanation: "CSS nesting стал стандартом в 2023. .card { &:hover { } .title { } } — вложенность как в SASS, но нативно без компиляции.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое prefers-color-scheme?",
    options: ["Пользовательская цветовая тема", "CSS медиазапрос для определения системной темы (светлой/тёмной) пользователя", "Тип переменной", "Настройка браузера"],
    answer: 1,
    explanation: "@media (prefers-color-scheme: dark) { } — автоматическая тёмная тема на основе системных настроек без JS.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое popover API?",
    options: ["jQuery плагин", "Нативный браузерный API для создания всплывающих элементов (тултипы, меню) без JS", "CSS-свойство", "Тип модального окна"],
    answer: 1,
    explanation: "<div popover id='tip'> + <button popovertarget='tip'> — браузер управляет показом, фокусом и закрытием. Нативно, доступно, без библиотек.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое CSS @layer?",
    options: ["CSS слои для z-index", "Директива для явного управления порядком каскада через именованные слои", "Тип импорта", "Аналог z-index"],
    answer: 1,
    explanation: "@layer base, components, utilities { } — слои имеют приоритет по порядку объявления. Решает войны специфичности в больших проектах.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое scroll-driven animations?",
    options: ["jQuery scroll анимации", "Нативные CSS-анимации, привязанные к позиции скролла через animation-timeline: scroll()", "Тип IntersectionObserver", "requestAnimationFrame на scroll"],
    answer: 1,
    explanation: "animation-timeline: scroll() — анимация прогрессирует со скроллом страницы. Без JS, без scroll listeners, работает на GPU.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое importmap в браузере?",
    options: ["Карта импортов webpack", "HTML-тег для управления разрешением ES-модулей в браузере без бандлера", "npm конфигурация", "Тип Service Worker"],
    answer: 1,
    explanation: "<script type='importmap'> позволяет писать import 'react' в браузере без бандлера, указав URL в карте. Нативный аналог алиасов.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое HTTP Early Hints (103)?",
    options: ["Ранний редирект", "Статус 103: сервер отправляет подсказки о ресурсах (preload) до финального ответа 200", "Тип кэша", "Предзагрузка DNS"],
    answer: 1,
    explanation: "103 Early Hints позволяет серверу отправить <link rel=preload> заголовки пока ещё готовит HTML. Браузер начинает загрузку ресурсов раньше.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое Priority Hints (fetchpriority)?",
    options: ["Приоритет fetch запроса", "Атрибут fetchpriority='high/low/auto' для управления приоритетом загрузки ресурсов браузером", "HTTP-заголовок", "Тип preload"],
    answer: 1,
    explanation: "<img fetchpriority='high' src='hero.jpg'> — явно повышаем приоритет LCP-изображения. Браузер лучше приоритизирует загрузку ресурсов.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое Speculation Rules API?",
    options: ["Оптимизация спекулятивного кода", "API для декларативного prefetch/prerender страниц которые пользователь скорее всего откроет", "Тип Service Worker", "Предзагрузка шрифтов"],
    answer: 1,
    explanation: "<script type='speculationrules'> — браузер заранее загружает или рендерит вероятные следующие страницы. Мгновенная навигация.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое font-display в @font-face?",
    options: ["Размер шрифта", "Стратегия отображения шрифта во время загрузки: swap, optional, fallback, block", "Тип шрифта", "Семейство шрифтов"],
    answer: 1,
    explanation: "font-display: swap — сразу показывает fallback, потом меняет (FOUT). optional — если шрифт не загрузился быстро, не использует его вовсе (лучший для CLS).",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое color-scheme CSS свойство?",
    options: ["Цветовая палитра", "Сообщает браузеру какие цветовые схемы (light/dark) поддерживает элемент для нативной стилизации форм", "Тип CSS-переменной", "Медиазапрос"],
    answer: 1,
    explanation: ":root { color-scheme: light dark } — встроенные элементы (input, select, scrollbar) автоматически меняют стиль под тему системы.",
  },
  {
    category: "web", label: "🌍 Web / Frontend",
    question: "Что такое anchor positioning в CSS?",
    options: ["Стилизация тега <a>", "Новый CSS API для позиционирования элемента (тултип, попап) относительно anchor-элемента", "Абсолютное позиционирование", "Тип float"],
    answer: 1,
    explanation: "anchor-name: --btn на кнопке и position-anchor: --btn на тултипе — CSS сам следит за позицией без JS. Заменяет Popper.js.",
  },
];

webQuestions.push(...extraWebQuestions);

module.exports = webQuestions;
